# Generated by Django 4.2.5 on 2023-10-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='imgage',
            new_name='image',
        ),
    ]
